fix - add env

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,5 @@
 name: Run Tests
+environment: mongo db
 
 
 on:
@@ -27,8 +28,16 @@ jobs:
         run: npm install
 
 
+      - name: Validate Environment Variables
+        run: |
+          if [ -z "${{ secrets.MONGODB_URI }}" ]; then
+            echo "❌ ERROR: MONGODB_URI secret não está definido!"
+            exit 1
+          fi
+          echo "✅ Secrets validadas com sucesso"
+
       - name: Run tests
         env:
           MONGODB_URI: ${{ secrets.MONGODB_URI }}
-          PORT: ${{ vars.PORT }}
+          PORT: ${{ vars.PORT || '3000' }}
         run: npm test
